// FORMAT: City Name: Department Name
//  City Name: You can get from Dialogflow entities
//  Department Name: You can get from Rocketchat endpoint/UI
// Note: Everything is case sensitive here

export const CityToDepartmentMap = {
    'Araranguá': 'Araranguá',
    'Balneário Camboriú': 'Balneário Camboriú',
    'Biguaçu': 'Biguaçu',
    'Blumenau': 'Blumenau',
    'Braço do Norte': 'Braço do Norte',
    'Campos Novos': 'Campos Novos',
    'Chapecó': 'Chapecó',
    'Criciúma': 'Criciúma',
    'Curitibanos': 'Curitibanos',
    'Floriaponolis': 'Floriaponolis',
    'Forquilinha': 'Forquilinha',
    'Garopaba': 'Garopaba',
    'Gaspar': 'tSTWZZELDmdGJovPm',
    'Içara': 'Içara',
    'Imbituba': 'Imbituba',
    'Itajaí': 'Itajaí',
    'Jaraguá do Sul': 'Jaraguá do Sul',
    'Joinville': 'Joinville',
    'Lajes': 'Lajes',
    'Lauro Muller': 'Lauro Muller',
    'Luiz Alves': 'Luiz Alves',
    'Mafra': 'Mafra',
    'Maravilha': 'Maravilha',
    'Morro da Fumaça': 'Morro da Fumaça',
    'navegantes': 'navegantes',
    'Nova Veneza': 'Nova Veneza',
    'Orleans': 'cHT7NRn67sYqnP7S7',
    'Otacilio Costa': 'Otacilio Costa',
    'Palhoça': 'Palhoça',
    'Presidente Getulio': 'Presidente Getulio',
    'Rio do Sul': 'Rio do Sul',
    'Santo Amaro da Imperatriz': 'Santo Amaro da Imperatriz',
    'São Bento do Sul': 'São Bento do Sul',
    'São Francisco do Sul': 'São Francisco do Sul',
    'São José': 'São José',
    'São Miguel D’Oeste': 'São Miguel D’Oeste',
    'Serra Alta': 'Serra Alta',
    'Sideropolis': 'Sideropolis',
    'Sombrio': 'Sombrio',
    'Tubarão': 'Tubarão',
    'Turvo': 'Turvo',
    'Urussanga e Xanxere': 'Urussanga e Xanxere'
};
